import { CounterpartyCardProps } from "../HomeCounterpartyCard/HomeCounterpartyCard";

export const CounterpartyMockData: CounterpartyCardProps[] = [
  {
    title: "Cathay Pacific",    
    country: "Hong Kong",
    tier: "1",
    annualValue: "3.2",
    annualDate: "31/09/2023",
    annualDateValue: "12M",
    indicativeValue: "4.6",
    indicativeDate: "31/09/2023",
    indicativeDateValue: "TTM",
  },
  {
    title: "Cathay Pacific",    
    country: "Hong Kong",
    tier: "1",
    annualValue: "3.2",
    annualDate: "31/09/2023",
    annualDateValue: "12M",
    indicativeValue: "4.6",
    indicativeDate: "31/09/2023",
    indicativeDateValue: "TTM",
  },
  {
    title: "Cathay Pacific",    
    country: "Hong Kong",
    tier: "1",
    annualValue: "3.2",
    annualDate: "31/09/2023",
    annualDateValue: "12M",
    indicativeValue: "4.6",
    indicativeDate: "31/09/2023",
    indicativeDateValue: "TTM",
  },
  {
    title: "Cathay Pacific",    
    country: "Hong Kong",
    tier: "1",
    annualValue: "3.2",
    annualDate: "31/09/2023",
    annualDateValue: "12M",
    indicativeValue: "4.6",
    indicativeDate: "31/09/2023",
    indicativeDateValue: "TTM",
  },
  {
    title: "Cathay Pacific",    
    country: "Hong Kong",
    tier: "1",
    annualValue: "3.2",
    annualDate: "31/09/2023",
    annualDateValue: "12M",
    indicativeValue: "4.6",
    indicativeDate: "31/09/2023",
    indicativeDateValue: "TTM",
  },
  {
    title: "Cathay Pacific",    
    country: "Hong Kong",
    tier: "1",
    annualValue: "3.2",
    annualDate: "31/09/2023",
    annualDateValue: "12M",
    indicativeValue: "4.6",
    indicativeDate: "31/09/2023",
    indicativeDateValue: "TTM",
  },
  {
    title: "Cathay Pacific",    
    country: "Hong Kong",
    tier: "1",
    annualValue: "3.2",
    annualDate: "31/09/2023",
    annualDateValue: "12M",
    indicativeValue: "4.6",
    indicativeDate: "31/09/2023",
    indicativeDateValue: "TTM",
  },
  {
    title: "Cathay Pacific",    
    country: "Hong Kong",
    tier: "1",
    annualValue: "3.2",
    annualDate: "31/09/2023",
    annualDateValue: "12M",
    indicativeValue: "4.6",
    indicativeDate: "31/09/2023",
    indicativeDateValue: "TTM",
  },
  {
    title: "Cathay Pacific",    
    country: "Hong Kong",
    tier: "1",
    annualValue: "3.2",
    annualDate: "31/09/2023",
    annualDateValue: "12M",
    indicativeValue: "4.6",
    indicativeDate: "31/09/2023",
    indicativeDateValue: "TTM",
  },
  {
    title: "Cathay Pacific",    
    country: "Hong Kong",
    tier: "1",
    annualValue: "3.2",
    annualDate: "31/09/2023",
    annualDateValue: "12M",
    indicativeValue: "4.6",
    indicativeDate: "31/09/2023",
    indicativeDateValue: "TTM",
  },
  {
    title: "Cathay Pacific",    
    country: "Hong Kong",
    tier: "1",
    annualValue: "3.2",
    annualDate: "31/09/2023",
    annualDateValue: "12M",
    indicativeValue: "4.6",
    indicativeDate: "31/09/2023",
    indicativeDateValue: "TTM",
  },
  {
    title: "Cathay Pacific",    
    country: "Hong Kong",
    tier: "1",
    annualValue: "3.2",
    annualDate: "31/09/2023",
    annualDateValue: "12M",
    indicativeValue: "4.6",
    indicativeDate: "31/09/2023",
    indicativeDateValue: "TTM",
  },
  {
    title: "Cathay Pacific",    
    country: "Hong Kong",
    tier: "1",
    annualValue: "3.2",
    annualDate: "31/09/2023",
    annualDateValue: "12M",
    indicativeValue: "4.6",
    indicativeDate: "31/09/2023",
    indicativeDateValue: "TTM",
  },
  {
    title: "Cathay Pacific",    
    country: "Hong Kong",
    tier: "1",
    annualValue: "3.2",
    annualDate: "31/09/2023",
    annualDateValue: "12M",
    indicativeValue: "4.6",
    indicativeDate: "31/09/2023",
    indicativeDateValue: "TTM",
  },
  {
    title: "Cathay Pacific",    
    country: "Hong Kong",
    tier: "1",
    annualValue: "3.2",
    annualDate: "31/09/2023",
    annualDateValue: "12M",
    indicativeValue: "4.6",
    indicativeDate: "31/09/2023",
    indicativeDateValue: "TTM",
  },
  {
    title: "Cathay Pacific",    
    country: "Hong Kong",
    tier: "1",
    annualValue: "3.2",
    annualDate: "31/09/2023",
    annualDateValue: "12M",
    indicativeValue: "4.6",
    indicativeDate: "31/09/2023",
    indicativeDateValue: "TTM",
  },
];
